### ISSUE TITLE
Clarify explicit version bumping

### ISSUE THREAD

**Issue by agronholm** [mathieudutour/github-tag-action#1]
The documentation states for `default_bump`:
> Which type of bump to use when none explicitly provided

So how *does* one explicitly provide the bump then?

**Comment by mathieudutour** [comment]
I added some docs: https://github.com/mathieudutour/github-tag-action/tree/master#bumping

Be sure to use the v2 of the action

**Comment by agronholm** [comment]
Thanks for the clarification.
