### ISSUE TITLE
There is no v6.0?

### ISSUE THREAD

**Issue by napulen** [mathieudutour/github-tag-action#107]
The README mentions `github-tag-action@v6.0`, but that release doesn't exist.

Getting an error from actions when I am trying this:

```
 Error: Unable to resolve action `mathieudutour/github-tag-action@v6.0`, unable to find version `v6.0`
```

Change the example in the README to `v5.6`?

**Comment by mathieudutour** [comment]
I know I'm trying to push the branch but it's timing out all the time. I'll try again

**Comment by mathieudutour** [comment]
Has anyone seen that before?
<img width="511" alt="image" src="https://user-images.githubusercontent.com/3254314/143590291-b7874b98-b28d-4497-bcae-d83008595ab6.png">

**Comment by mathieudutour** [comment]
ah it finally worked
