### ISSUE TITLE
Can you please clarify what keyword in commit message can trigger a minor and major version bump?

### ISSUE THREAD

**Issue by kwang7nyc** [mathieudutour/github-tag-action#112]
E.g I included "BREAKING CHANGE" in my commit message, however, it doesn't trigger major version bump.
Although you've mentioned that we should refer to this Angular commit message convention, https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#-git-commit-guidelines, it's still not clear which keyword gonna map to which version bump.

Thanks in advance!

**Comment by mathieudutour** [comment]
see https://github.com/mathieudutour/github-tag-action/issues/91#issuecomment-889831674
