### ISSUE TITLE
commit with message "perf(pencil): remove graphiteWidth option", but no major tag created

### ISSUE THREAD

**Issue by ozbillwang** [mathieudutour/github-tag-action#117]
Follow the README, I did tests with three commit messages:

case 1 : Any commits

case 2: feat(pencil): add 'graphiteWidth' option

case 3: perf(pencil): remove graphiteWidth option

I got patch tag bump with case 1, and minor tag bump with case 2. 

But I didn't get major tag bump with case 3. 

So how can I get **major** tag bumped and released?

**Comment by mathieudutour** [comment]
See https://github.com/mathieudutour/github-tag-action/issues/91#issuecomment-889831674
