### ISSUE TITLE
Server Error

### ISSUE THREAD

**Issue by Naspo88** [mathieudutour/github-tag-action#119]
This morning the action started to launch this error:
<img width="496" alt="Capture" src="https://user-images.githubusercontent.com/7783148/156369324-d22d6717-d5b3-409d-9285-084eee3573ce.PNG">

Any help?

**Comment by suyog-fp** [comment]
@mathieudutour any ideas on this issue?

**Comment by mathieudutour** [comment]
I'm guessing it's GitHub that is down.

**Comment by suyog-fp** [comment]
I am still getting issue. what about you @Naspo88 ?
