### ISSUE TITLE
No commits found

### ISSUE THREAD

**Issue by fabioAtANT** [mathieudutour/github-tag-action#130]
Hi

One of my github actions fails because no commits are found in the github-tag-action. The same repo contains three GitHub-Actions and two are working correctly. Any hints what could be the problem?

Run mathieudutour/github-tag-action@v5.5
Previous tag was api/0.0.0, previous version was 0.0.0.
Analysis of 0 commits complete: no release
New version is 0.0.1.
New tag after applying prefix is api/0.0.1.

checkout task is defined as follow:
      - name: Checkout
        uses: actions/checkout@v2

best
f

**Comment by pasres** [comment]
This issue can be fixed by setting the option:
`fetch_all_tags: true`
this way it fetches all tags, instead of only the last 100 and thus is able to analyze commits/determine tag
note: this requires v5.6 or higher
