### ISSUE TITLE
The node12 is not supported on macOS ARM64 platform. Use node16 instead.

### ISSUE THREAD

**Issue by paulz** [mathieudutour/github-tag-action#144]
when we ran this action on self hosted M1 machine we get this warning:

`The node12 is not supported on macOS ARM64 platform. Use node16 instead.`

would it be possible to update to node16?

**Comment by chrisjohnson00** [comment]
node12 is deprecated for github actions, in favor of node16

**Comment by sneakyvv** [comment]
It's also deprecated for GitHub Actions in general. See https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
