### ISSUE TITLE
The `set-output` command is deprecated and will be disabled soon.

### ISSUE THREAD

**Issue by paulz** [mathieudutour/github-tag-action#155]
Thank you for the awesome GitHub action!

Works great, but we are getting this warning:

>  The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by smkjason** [comment]
Hey @paulz,

I believe this is resolved by the following PR: https://github.com/mathieudutour/github-tag-action/pull/146 Hope this helps.

**Comment by paulz** [comment]
thank you!
