### ISSUE TITLE
empty parentheses after every change in the changelog

### ISSUE THREAD

**Issue by moodysalem** [mathieudutour/github-tag-action#16]
https://github.com/Uniswap/uniswap-frontend/releases/tag/v2.0.8

**Comment by mathieudutour** [comment]
should be fixed in v4.5 (the parentheses should contain the commit hash)

**Comment by moodysalem** [comment]
something broke
https://github.com/Uniswap/uniswap-frontend/runs/713825606

**Comment by mathieudutour** [comment]
Ah sorry, if you restart the job it should work
