### ISSUE TITLE
Deprecation warning: set-output to be disabled on May 31st, 2023

### ISSUE THREAD

**Issue by ryanberckmans** [mathieudutour/github-tag-action#164]
When using this action:
```
The `set-output` command is deprecated and will be disabled soon.
Please upgrade to using Environment Files. For more information see:
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by KyleBrown-804** [comment]
What version are you using? I recently went through these upgrades myself and upgrading to v6.1 solved my deprecation warnings.

v6.1 is using node 16 here: https://github.com/mathieudutour/github-tag-action/blob/releases/v6.1/action.yml#L64 and also has the update `actions/core` package here: https://github.com/mathieudutour/github-tag-action/blob/master/package.json#L24

**Comment by ryanberckmans** [comment]
Oops, I was accidentally using an older version than I thought I was. Thanks.
