### ISSUE TITLE
chores commits not in changelog

### ISSUE THREAD

**Issue by moodysalem** [mathieudutour/github-tag-action#17]
https://github.com/Uniswap/uniswap-frontend/compare/v2.0.8...v2.0.9
https://github.com/Uniswap/uniswap-frontend/releases/tag/v2.0.9
https://github.com/Uniswap/uniswap-frontend/runs/716658169?check_suite_focus=true

**Comment by mathieudutour** [comment]
I think it's because it only shows commits that have an impact on a release and `chores` don't? Not sure

**Comment by moodysalem** [comment]
maybe, weird though because the first major release was triggered with a chore release (with v4 of the plugin)
https://github.com/Uniswap/uniswap-frontend/releases/tag/v2.0.0

**Comment by mathieudutour** [comment]
It should work now
