### ISSUE TITLE
Update action to use Node 20 or newer

### ISSUE THREAD

**Issue by mhemani-reach** [mathieudutour/github-tag-action#198]
Node 16 is EOL and Github Actions is deprecating it in Spring 2024. Please update the action to Node 20.
More info: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

**Comment by mhemani-reach** [comment]
https://github.com/mathieudutour/github-tag-action/issues/198

**Comment by naresh-gn** [comment]
Created a PR to upgrade to node20, if some from admin can take a look at it https://github.com/mathieudutour/github-tag-action/pull/202

**Comment by dfeldick** [comment]
Please? Would really like to see the warnings removed from my gitlab action.

**Comment by ayyadalaa** [comment]
Same, I wish this gets addressed.

**Comment by mhemani-reach** [comment]
Github will be migrating to run all actions by default on Node 20 on May 13, 2024
@mathieudutour can you review and merge https://github.com/mathieudutour/github-tag-action/pull/202 if there's no remaining blockers?
