### ISSUE TITLE
Custom tag not being picked up

### ISSUE THREAD

**Issue by ankushj-sapientai** [mathieudutour/github-tag-action#206]
Hi, I pushed 1 custom tag like this->
`custom_tag: "2024.1.010"`
and
`custom_tag:2024.1.010`

in both the cases, when in the next run I remove the custom_tag field, it still takes the older 2024.1.009 tag as the previous tag, why is that?

**Comment by Machine391** [comment]
I think I messed up the logic , maybe too many field priorities. I am looking for help developing the programs that aren't fully functional.  I create a lot of different tools.

**Comment by Machine391** [comment]
Try 2024.1.09 then 2024.1.10

**Comment by ankushj-sapientai** [comment]
Was doing it wrong, my bad. Needs to be in correct Semver format, does’t recognize x.y.009 but recognizes x.y.9.
