### ISSUE TITLE
Support pre-releases

### ISSUE THREAD

**Issue by Fresa** [mathieudutour/github-tag-action#25]
It would be nice to have support for pre-releases. I tend to pre-release everything that is not on master (my release branch) by using the same functionality that is used for creating releases except tagging them with a pre-release tag of choice according to the semver 2.0.0 specification https://semver.org/#spec-item-9.

Suggestion:
- Add a `pre_release_branches` input that similar to `release_branches` specifies which branches should be treated as pre-releases. Default to no branches in order to not break current behaviour.
- Add a `append_to_pre_release_tag` input to define what should be appended to the pre-release tag according to semver 2.0.0 specification https://semver.org/#spec-item-9

Versioning release branches should follow the latest version from any pre-releases on the branch being merged into the release branch.

**Comment by Wndrr** [comment]
I'm really interessiere in this feature aswell. I looked at the code with the intention of making a pull-request but because of my lack of familiarity with Typescript I gave up for now. @mathieudutour let me know if you have no intention of implementing this yourself. I'll look into learning what I need to do so in this case.

**Comment by mathieudutour** [comment]
> if you have no intention of implementing this yourself

I don't really have time to work on this project anymore sorry. But happy to review and merge a PR!

**Comment by boxcee** [comment]
@Fresa Try my branch if you have time. Looking for feedback: `boxcee/github-tag-action@prereleases`.

**Comment by mathieudutour** [comment]
fixed in v5

**Comment by Fresa** [comment]
@boxcee You were too fast for me! I'll try to have a look this evening. Good work! 🥇

**Comment by Fresa** [comment]
@boxcee: The pre-release tag is not correctly calculated when commiting to a pre-release branch that already as a pre-release tag. It seems the action does not find previously created pre-release tags on the current branch.

Another interesting scenario I'm not sure you have thought about is what should happen when you merge a pre-release branch into another pre-release branch? Their versions need to be synced somehow, maybe by choosing the highest version of the two branches?

https://github.com/Fresa/Port/actions/runs/356302464
![image](https://user-images.githubusercontent.com/1190300/98709397-9f48c880-2382-11eb-9892-bb28422998ab.png)

https://github.com/Fresa/Port/actions/runs/356308542
![image](https://user-images.githubusercontent.com/1190300/98709451-ae2f7b00-2382-11eb-93ac-7d77ae860f6c.png)

**Comment by boxcee** [comment]
@Fresa Damn, yes, you are right a bug in there... Opened another PR for it: https://github.com/mathieudutour/github-tag-action/pull/38

To your second question:

Depends on how you use the `append_to_pre_release_tag` feature. If it is set to `prerelease` in both branches (like in your test), both branches will increment the same `prerelease` tag. In case you merge there won't be any conflict.

If you don't set it and it uses the branch name you also don't have a conflict since two different tags are used.

Is this what you mean?

**Comment by boxcee** [comment]
@Fresa #38 was just merged!

**Comment by mathieudutour** [comment]
i updated v5 with the fix

**Comment by Fresa** [comment]
@boxcee Let's say I have one commit on master tagged with 1.0.0, which is my only release branch.
```
git tag --merged master --sort=taggerdate
1.0.0
```

1. I branch branch1 from master, and implement a feature creating 1.1.0-branch1.0 tag on branch1.
```
git tag --merged branch1 --sort=taggerdate
1.0.0
1.1.0-branch1.0
```

2. I branch branch2 from master, and implement a patch creating 1.0.1-branch2.0 on that branch.
```
git tag --merged branch2 --sort=taggerdate
1.0.0
1.0.1-branch2.0
```

3. I merge branch1 into master, causing master to be released as 1.1.0.
```
git tag --merged master --sort=taggerdate
1.0.0
1.1.0-branch1.0
1.1.0
```

4. I commit another patch to branch2 creating tag 1.0.1-branch2.1
```
git tag --merged branch2 --sort=taggerdate
1.0.0
1.0.1-branch2.0
1.0.1-branch2.1
```

5. I merge from master into branch2, causing that branch to have release tags in the following order:
```
git tag --merged branch2 --sort=taggerdate
1.0.0
1.1.0-branch1.0
1.0.1-branch2.0
1.1.0
1.0.1-branch2.1
```

If I then commit another patch on branch2, what will the resulting commit be released as? 
1.0.1-branch2.2? 
1.1.1-branch2.0?

**Comment by boxcee** [comment]
It should result in `1.1.1-branch2.0`.

Sidenote: Currently there is no way to create a `1.1.0-branch1.0` prerelease tag from a `1.0.0` tag. It would require a commit which would result in the release type `preminor`. Not implemented at the moment as far as I can tell.

**Comment by Fresa** [comment]
So if I on branch1 (step 1 above) commit a change with the following commit message:
`feat(cool): My cool feature`

What release tag would that result in for that commit on branch1?

**Comment by boxcee** [comment]
Maybe to further elaborate how the tagging is currently calculated.

Generally on tags:
1. Github API is used to query all repository tags.
2. Invalid semver tags are removed.
3. Valid semver tags are ordered in descending order.

Pre-release tags:
1. Same as above.
2. Tags which do **not** match the pre-release identifier (either default: `<branch>`  or `append_to_pre_release_tag`) are removed.
3. The latest **non**-pre-release tag is determined.
4. The latest pre-release tag is determined.

Let's say your repository has these tags (simplified):
- `1.0.0`
- `1.0.1`
- `2.2.1-branch1.0`
- `2.1.5`
- `1.2.3-branch2.0`
- `release-3.2.1`

After first step - filtering for valid tags - only these tags are left:
- `1.0.0`
- `1.0.1`
- `2.2.1-branch1.0`
- `2.1.5`
- `1.2.3-branch2.0`

After second steps, tags are ordered like this:
- `1.0.0`
- `1.0.1`
- `2.2.1-branch1.0`
- `2.1.5`
- `1.2.3-branch2.0`

> So if I on branch1 (step 1 above) commit a change with the following commit message:
> `feat(cool): My cool feature`
> 
> What release tag would that result in for that commit on branch1?

`1.0.1-branch1.0`

**Comment by boxcee** [comment]
Maybe to further elaborate how the tagging is currently calculated.

Generally on tags:
1. Github API is used to query all repository tags.
2. Invalid semver tags are removed.
3. Valid semver tags are ordered in descending order.

Pre-release tags:
1. Same as above.
2. Tags which do **not** match the pre-release identifier (either default: `<branch>`  or `append_to_pre_release_tag`) are removed.
3. The latest **non**-pre-release tag is determined.
4. The latest pre-release tag is determined.

Let's say your repository has these tags (simplified):
- `1.0.0`
- `1.0.1`
- `2.2.1-branch1.0`
- `2.1.5`
- `1.2.3-branch2.0`
- `release-3.2.1`
- `2.2.0`

After first step - filtering for valid tags - only these tags are left:
- `1.0.0`
- `1.0.1`
- `2.2.1-branch1.0`
- `2.1.5`
- `1.2.3-branch2.0`
- `2.2.0`

After second step - sort in descending order - tags are ordered like this:
- `2.2.1-branch1.0`
- `2.2.0`
- `2.1.5`
- `1.2.3-branch2.0`
- `1.0.1`
- `1.0.0`

Now on the `branch1` valid tags are filtered again for pre-release tags to
match the pre-release identifier. Result would be:
- `2.2.1-branch1.0`
- `2.2.0`
- `2.1.5`
- `1.0.1`
- `1.0.0`

On `branch2` it would look like this:
- `2.2.0`
- `2.1.5`
- `1.2.3-branch2.0`
- `1.0.1`
- `1.0.0`

The first tag is always used to base off the next release type. Does that make sense?

**Comment by Fresa** [comment]
I would expect the pre-release branches to follow the same semantic release conventions as the release branches do. What happens when the pre-release branch get merged to a release branch? Is the release created by the merge recalculated according to the semantic release conventions based on the previous non-prerelease?

**Comment by boxcee** [comment]
@Fresa This seems to be less a question of how what is right than what is being supported. [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0-beta.2/#specification) or [Angular Git Commit](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#-git-commit-guidelines) simply don't specify any keywords for `premajor`, `preminor`, `prepatch` or `prerelease` releases. And these projects are the base for this project.

Additionally this project adds support for `prereleases` (`prepatch`) by specifying a branch.

Once you are committing to a `prerelease` branch, all commit messages are basically being ignored as you already specified them as `prerelease`.

**Comment by Fresa** [comment]
I'm refering to semver versioning. Pre-releases follow the same versioning strategy as non-pre-releases.

**Comment by boxcee** [comment]
Using the release types and starting with `1.0.0`:
```
prerelease
minor
minor
```
will get you `1.2.0`.

```
prerelease
prerelease
preminor
minor
preminor
```
will get you `1.2.0-prerelease.0`.

I think the parsing done here is correct. It is simply for the lack of some keywords that there are no other increments possible.

**Comment by boxcee** [comment]
Here is the sample code I used:
```bash
#! /bin/env node

const semver = require('semver');
const {analyzeCommits} = require('@semantic-release/commit-analyzer');

const commits = [
    {message: "prepatch: something"},
    {message: "fix: something"},
    {message: "fix: something"},
    {message: "fix: something"},
    {message: "fix: something"},
    {message: "fix: something"},
]

analyzeCommits(
    {},
    {commits, logger: {log: console.info.bind(console)}}
).then(console.log);


const version = semver.parse('0.0.1');
const identifier = 'branch1';
const patch = semver.inc(version, 'patch', identifier);
console.log(patch);
// => 0.0.2

const premajor = semver.inc(patch, 'premajor', identifier);
console.log(premajor);
// => 1.0.0-branch1.0

const premajor2 = semver.inc(premajor, 'premajor', identifier);
console.log(premajor2);
// => 2.0.0-branch1.0

const prerelease = semver.inc(premajor2, 'prerelease', identifier);
console.log(prerelease);
// => 2.0.0-branch1.1
```

**Comment by boxcee** [comment]
Actually. I may be very wrong.

**Comment by boxcee** [comment]
@Fresa #41 Should allow correct versioning even on prerelease branches. It includes a feature to also set `custom_release_rules`.

**Comment by Fresa** [comment]
not sure why you would need that, the action should already knows the commit is on a pre-release branch?

**Comment by boxcee** [comment]
Optional to use commit messages like: `hotfix: null check` to trigger a `patch` release.

**Comment by Fresa** [comment]
I think I need to fiddle a bit with this to get a better sense how it works :) 

Great work though! 👍
