### ISSUE TITLE
`new_tag` output behaviour is ambiguous

### ISSUE THREAD

**Issue by sebbacon** [mathieudutour/github-tag-action#26]
Based on the parts highlighted in red below, I expected `new_tag` output to be undefined for non-release branches.

![image](https://user-images.githubusercontent.com/211271/91734513-ece6cf00-eba2-11ea-820b-5148bd1924d1.png)

**Comment by boxcee** [comment]
Maybe the wording should be changed a little here.

There are two things here:
1. The repository tag.
2. The output called new_tag.

The first will only be created on `release_branches` (and with v5 on `prerelease_branches`).
The second will be created always, except there have been no commits.
