### ISSUE TITLE
Support for 'custom_tag' input

### ISSUE THREAD

**Issue by bissim** [mathieudutour/github-tag-action#28]
Hello,
Will you support the `custom_tag` input variable to manually specify tag, like in [anothrNick/github-tag-action](https://github.com/anothrNick/github-tag-action)?

**Comment by mathieudutour** [comment]
happy to accept a PR

**Comment by bissim** [comment]
In [laputansoft/github-tag-action](https://github.com/laputansoft/github-tag-action) fork there's an example of how to introduce such support, although this specific implementation appends latest commit to version.

As soon as I'll have some spare time, I'll give a try to implement it.

**Comment by bissim** [comment]
I hope my attempt to integrate is good enough to pass.
