### ISSUE TITLE
Please create a new release for the latest change

### ISSUE THREAD

**Issue by gdlcf88** [mathieudutour/github-tag-action#30]
I inputted "custom_tag" and get the error
```
##[warning]Unexpected input(s) 'custom_tag', valid inputs are ['github_token', 'default_bump', 'tag_prefix', 'release_branches', 'create_annotated_tag', 'dry_run']
```
since the "custom_tag" feature is not in the v4.5 release.

**Comment by bissim** [comment]
@gdlcf88, try to specify `master` as action version: if I got this right, it's a valid version value for _master_ branch.

**Comment by mathieudutour** [comment]
`master` won't work because there isn't the dependencies checked in.

I published the new version - sorry for the delay
