### ISSUE TITLE
git rev-list --tags --max-count=1 can return older tags first

### ISSUE THREAD

**Issue by martinsbalodis** [mathieudutour/github-tag-action#4]
From git docs the git rev-list command returns commits in "reverse chronological order". After doing some `git rebase`ing I got into a situation where this command didn't return the latest tag but instead returned one before. As a result the action tried to create a tag that already existed.

This could be fixed by changing:
```
git rev-list --tags --max-count=1
```
to:
```
git rev-list --tags --topo-order --max-count=1
```

**Comment by mathieudutour** [comment]
Ah weird. Do you want to send a PR?
