### ISSUE TITLE
Increment major version is not working

### ISSUE THREAD

**Issue by boxcee** [mathieudutour/github-tag-action#40]
While trying to figure out how to increase pre-release versions via preminor, prepatch etc. I realized increments of major versions are not working at the moment.

https://github.com/boxcee/test-github-action/actions/runs/359492860

https://github.com/boxcee/test-github-action/actions/runs/359503929

**Comment by mathieudutour** [comment]
What makes you say that?

**Comment by boxcee** [comment]
Look at the commit messages from the two commits. One uses `BREAKING CHANGE:` and the other `perf(pencil):`. Neither of them incremented the `major` version.

**Comment by boxcee** [comment]
Started writing some tests to nail this down.

**Comment by mathieudutour** [comment]
Yeah that's because it should be
```
commit message

BREAKING CHANGE: in the commit body
```

**Comment by boxcee** [comment]
Ah, gotcha!

**Comment by mathieudutour** [comment]
But adding some tests is a good idea 😄
