### ISSUE TITLE
v5 README on marketplace includes custom_release_rules input, but not actually recognized as input

### ISSUE THREAD

**Issue by rnoda** [mathieudutour/github-tag-action#43]
Hello,

First, I'd like to thank you for your great work and the functionality you have provided with this action.

I recently wanted to make use of the "custom_release_rules" input. It is documented in the README as well as it seems to be available already as it appears on the action details in the marketplace.

However, I get a warning in the workflow indicating the input is not valid.

When will this be available?

Thanks!
![screenshot](https://user-images.githubusercontent.com/7172402/100905096-ab153f80-3495-11eb-9792-6975a7d44242.png)

**Comment by mathieudutour** [comment]
ah sorry, it's in the v5.1
