### ISSUE TITLE
Support main as the default branch

### ISSUE THREAD

**Issue by NasAmin** [mathieudutour/github-tag-action#45]
Hi,

Thanks for this action!

Due to historic connotations associated with the word master, people have started renaming their default branch from master to main. GitHub have opted for `main` but people can any name
https://sfconservancy.org/news/2020/jun/23/gitbranchname/

In order to support this, I propose this action be udpated to take the default branch as an input. It can be left to master as a default for in which can it should be a minor release.
However, if we decide that this action will expect the default branch to be `main` then in that case it should be a breaking change/major version bump.

So can we set the default branch as an input? 
I have updated one of our repositories to have default branch name as `main` but this action is now not generating the correct version in the form of `major.minor.patch` anymore. It now suffixes the version with some random text.

I'd appreciate some guidance on this.

**Comment by mathieudutour** [comment]
you can set the `release_branches` to `main`

**Comment by NasAmin** [comment]
Thanks, I should have paid more attention to the docs.
