### ISSUE TITLE
Version inside package.json not updated

### ISSUE THREAD

**Issue by jsphkhan** [mathieudutour/github-tag-action#48]
This workflow module works fine with the patch, minor and major releases. 
The tags and release are generated correctly
However, the version inside **package.json** is not updated. For example, I did a Major release 1.0.0 - Release v1.0.0

The version inside package.json is not updating:
```
{
  "name": "mob-example",
  "version": "0.1.0"
}
```

Is this expected to behave this way? Ideally, your package.json version should be in sync with your current release version.

**Comment by mathieudutour** [comment]
this action is unrelated to nodejs and package.jsons. So yes it is expected not to change your files. You can use another action to modify your package.json and commit the change if you need to

**Comment by m-cat** [comment]
For anyone else finding this, here's something you can use:

https://github.com/phips28/gh-action-bump-version
