### ISSUE TITLE
Example from Readme dont work

### ISSUE THREAD

**Issue by steinbrueckri** [mathieudutour/github-tag-action#5]
see https://github.com/steinbrueckri/gha-test-repo/runs/386546174 for Example ...

**Comment by mathieudutour** [comment]
Ah right, we need to fetch the tags first. Weird that it worked for me without

Fixed by https://github.com/mathieudutour/github-tag-action/commit/1308fda63431c2c1d53f8e2ca5c16d3ae146e326

**Comment by steinbrueckri** [comment]
THX for the fast support ... you are awesome! ❤️ 👍
