### ISSUE TITLE
Semver increment not work with PR

### ISSUE THREAD

**Issue by DavoBR** [mathieudutour/github-tag-action#51]
I guess that calculating the origin branch of the PR can be a solution

```
Run mathieudutour/github-tag-action@v5
  with:
    github_token: ***
    dry_run: true
    default_bump: patch
    tag_prefix: v
    release_branches: master
    create_annotated_tag: false
Previous tag was 1.0.0.
Analysis of 0 commits complete: no release
Error: 1.0.1-refs/pull/3/merge.0 is not a valid semver.
```

**Comment by mathieudutour** [comment]
hum I don't think creating tags on PRs is a good idea. What's the use case?

**Comment by DavoBR** [comment]
In my case i don't creating tags on PRs, is just for build the artifact of the PR with the next version number.

i resolved that using the param: append_to_pre_release_tag

![image](https://user-images.githubusercontent.com/498724/103810109-0b694500-5031-11eb-8400-0156ce263cd9.png)
