### ISSUE TITLE
SemVer bumping is not working for Major version and pull requests

### ISSUE THREAD

**Issue by bhojjoshi** [mathieudutour/github-tag-action#52]
Getting below error for pull request:    
Error: 1.0.9-refs/pull/2/merge.0 is not a valid semver

For the major version upgrade, providing the "BREAKING CHANGE: message" is not bumping the major version rather bumping the patch version.

**Comment by mathieudutour** [comment]
> Getting below error for pull request:

Duplicates of #51 

> For the major version upgrade, providing the "BREAKING CHANGE: message" is not bumping the major version rather bumping the patch version.

The "BREAKING CHANGE" needs to be in the commit's body - not its title.

**Comment by koiralakiran1** [comment]
> > For the major version upgrade, providing the "BREAKING CHANGE: message" is not bumping the major version rather bumping the patch version.
> 
> The "BREAKING CHANGE" needs to be in the commit's body - not its title.

@mathieudutour Can you please elaborate how to trigger other version bumps (except patch) with an example commit message?
My commit message looks like: (`git commit -m "Test commit" -m "Minor"`)
![image](https://user-images.githubusercontent.com/11130898/103805202-632c9e00-507b-11eb-8693-6fb226a1c4bd.png)

And my `custom_release_rules` is:
![image](https://user-images.githubusercontent.com/11130898/103805340-89ead480-507b-11eb-909d-beaea9bf1ee9.png)

But it only bumps the patch version.
