### ISSUE TITLE
outputs.previous_tag is the previous version rather then the tag

### ISSUE THREAD

**Issue by ToMe25** [mathieudutour/github-tag-action#59]
I recently set this up for a new repo, and thought id use the new version 5.1, rather then the old version 4.2 that i used before.
While doing this i noticed that the value of outputs.previous_tag for the new tag v1.0.3 is 1.0.2 rather then v1.0.2.

**Comment by mathieudutour** [comment]
fixed in v5.2 which adds a `previous_version` output
