### ISSUE TITLE
Commits analysed repeatedly, affecting version bump multiple times.

### ISSUE THREAD

**Issue by andres99x** [mathieudutour/github-tag-action#62]
Hi Mathieu, 

I noticed that when working on a pre-release branch and committing progress to that branch, it's constantly recalculating the new version based on already analyzed commits. 

This happens because commits for analysis are always calculated based on the latestTag regardless of where are we "standing" on. (https://github.com/mathieudutour/github-tag-action/blob/master/src/action.ts#L66)

Please confirm if this is the expected behavior? If not, i believe the action should be aware of the context and determine the commits based on that context, so that it actually calculates the right commit diff and bump based only on those.

Please find the evidence here:

1. https://github.com/andres99x/submodule/actions/runs/594033597
2. https://github.com/andres99x/submodule/actions/runs/594037850
3. https://github.com/andres99x/submodule/actions/runs/594043298

The first action contains a patch and a minor commit, while the other two contains commits that shouldn't match a release type, but regardless of this each action execution bumps the version by a minor.

**Comment by mathieudutour** [comment]
happy to accept a PR to fix it
