### ISSUE TITLE
Is there a way to remove the suffix entirely?

### ISSUE THREAD

**Issue by Julian-IronForge** [mathieudutour/github-tag-action#64]
I'd like to remove the suffix from the tag and release name. Ideally the tag and release would be formatted thus: `v1.19.1`. I'm running this action on pushes to the `stable` branch and right now the formatting is: `v1.19.1-stable.0`. 

I've tried setting `append_to_pre_release_tag` to `null` and `""` but of course `null` just uses the default, and `""` isn't one of the available options.

**Comment by mathieudutour** [comment]
is `stable` your release branch in your inputs?

**Comment by Julian-IronForge** [comment]
Ah, no. That solves the issue, thank you!
