### ISSUE TITLE
(Discussion) Use 'conventionalcommits' preset instead of 'angular' to support custom changelog sections

### ISSUE THREAD

**Issue by koiralakiran1** [mathieudutour/github-tag-action#68]
Hi Mathieu,

I'm working on a fix for https://github.com/mathieudutour/github-tag-action/issues/54. I've mentioned why this is closed but not fixed in [this comment](https://github.com/mathieudutour/github-tag-action/issues/54#issuecomment-784392947).

So, before creating a PR for this, I just wanted to get your feedback beforehand on the approach that I'm taking.

Here's what I'm doing to fix this:
- Currently, the default preset used to `generateNotes` is [conventional-changelog-angular](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-angular) which doesn't support custom changelog sections but [conventionalcommits](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-conventionalcommits) does. (Reference: https://github.com/semantic-release/release-notes-generator/issues/153). I'm more inclined to using the preset instead of copying & pasting the `transform` function and modifying it to fit the use case.

https://github.com/mathieudutour/github-tag-action/blob/5961cf9c4dfdab0d0ca4bab9f1d2403960331ef8/src/action.ts#L148-L149

-  Right now, `custom_release_rules` supports `<keyword>:<release_type>`.  I'm thinking of adding another section to this that mentions the changelog section/title the commits in this group should persist in. i.e. `<keyword>:<release_type>:<changelog_section>`
Any support for gitmoji in the changelog section/title will already be supported after https://github.com/mathieudutour/github-tag-action/issues/67 is fixed.

- This last/new section will be optional whose default value will be what's used on `conventional-changelog-angular`. Any rules the user provides will override the rule, if it exists in the default rule else gets added with the default rule.

You can find my latest changes for this [here](https://github.com/mathieudutour/github-tag-action/compare/master...koiralakiran1:custom-release-rule-changelog?expand=1)

Let me know what you think

**Comment by mathieudutour** [comment]
That makes sense to me :+1:

We can discuss the implementation details in the PR

**Comment by jeremybdk** [comment]
That would definitely solve my issue, and would be great to be able to have more sections by default!

**Comment by koiralakiran1** [comment]
> That would definitely solve my issue, and would be great to be able to have more sections by default!

@jeremybdk,
For now, I've only included the sections used by angular to preserve the existing behavior.

@mathieudutour  Any comment?

**Comment by jeremybdk** [comment]
Actually there might be an issue, unless I'm missing something obvious that I don't see.

I'm using this repo to test the new version, but it's not working: https://github.com/jeremybdk/test-bump @koiralakiran1 I copied your workflow action, but I cannot find the issue, the changelog is still empty. Any Idea ?

It's working with feat but still not with chore ...

**Comment by koiralakiran1** [comment]
@jeremybdk 
Chore/chore is not a default rule or section mentioned in Angular's default rules. So you'll have to include a changelog section in your custom rule explicitly.

i.e. `chore:patch: Chores` where the last part is the section title in the changelog.

I didn't add additional rules in my PR to mock the previous behavior of the action which used Angular's default rules.

**Comment by jeremybdk** [comment]
@koiralakiran1 Sorry I missed that part, where I needed to include the changelog section, again thank you very much for your work!

**Comment by tomavic** [comment]
Do you know how to add the conventionalcommit preset in the commitanalyzer too?

This working example here just using a releaserules https://github.com/semantic-release/release-notes-generator/issues/153#issuecomment-555152563
