### ISSUE TITLE
output new_tag is set even if there are no commits

### ISSUE THREAD

**Issue by moodysalem** [mathieudutour/github-tag-action#85]
https://github.com/mathieudutour/github-tag-action#-outputs

new_tag is set with 0 commits, e.g.
see https://github.com/Uniswap/uniswap-interface/runs/2600558559?check_suite_focus=true

> Set output 'new_tag'

release ran, despite this if line https://github.com/Uniswap/uniswap-interface/blob/03108b981ea302d6d60014dd0da3cdd76441d63e/.github/workflows/release.yaml#L31

**Comment by moodysalem** [comment]
this happened again. how do we detect 'no release'? is this fixed? https://github.com/Uniswap/uniswap-interface/runs/3300463377?check_suite_focus=true

**Comment by mathieudutour** [comment]
it's because you have a default_bump. Set it to `false` and it should be fine

**Comment by moodysalem** [comment]
Thanks, it worked, but I do think it should be the default.

**Comment by mathieudutour** [comment]
that would be a breaking change. But I'd be happy to accept a PR to add some logging when the default_bump is used and what to do to change it
