### ISSUE TITLE
Feature request: Is it possible to get a dry-run argument added

### ISSUE THREAD

**Issue by ssoerensen** [mathieudutour/github-tag-action#9]
It would awesome to be able to do a dry run, this would enable us to use your action and update version numbers in readme files etc.

**Comment by mathieudutour** [comment]
How about if the branch doesn't match `release_branches`, we do a dry run? And we support `release_branches: none` not to match anything?

**Comment by ssoerensen** [comment]
That sounds like a fineish solution. I mean it it something that can be missed as a feature. IMHO, dry run is better because it would be explicit what it is configured to do.
