### ISSUE TITLE
Problem to bump major version

### ISSUE THREAD

**Issue by edersonmberti** [mathieudutour/github-tag-action#91]
I'm having a problem to bump major version. I created a commit with "perf" prefix and the result is a patch bump.

![image](https://user-images.githubusercontent.com/34242210/127529632-9dd418a9-c7e2-49f2-a0c2-e0908125b9b8.png)

Action: https://github.com/edersonmberti/github-actions-playground/actions/runs/1079322167

Anyone knows the reason or am i doing something wrong?

**Comment by mathieudutour** [comment]
you haven't specify a breaking change in your commit message.

```
perf(pencil): remove graphiteWidth option

BREAKING CHANGE: The graphiteWidth option has been removed.
The default graphite width of 10mm is always used for performance reasons.
```
see how `BREAKING CHANGE` is in the commit message body

**Comment by orkenstein** [comment]
> you haven't specify a breaking change in your commit message.
> 
> ```
> perf(pencil): remove graphiteWidth option
> 
> BREAKING CHANGE: The graphiteWidth option has been removed.
> The default graphite width of 10mm is always used for performance reasons.
> ```
> 
> see how `BREAKING CHANGE` is in the commit message body

But why this phrase? What else triggers MAJOR?

**Comment by mathieudutour** [comment]
If you don't have a breaking change, you don't need a new major version

**Comment by Rakhmanov** [comment]
Was also thrown off by that
