### ISSUE TITLE
Issues with append_to_pre_release_tag

### ISSUE THREAD

**Issue by saar-win12** [mathieudutour/github-tag-action#93]
`"append_to_pre_release_tag"`
Hey, there is an option to not use that? to set it boolean or something?
it bothers me and I don't need it.
it appends the name of the branch
![Screen Shot 2021-08-08 at 18 39 42](https://user-images.githubusercontent.com/62869607/128637601-df609baf-6c65-441f-ac71-836be4c53777.png)
I need only v2.2.2
thanks.

**Comment by mathieudutour** [comment]
you need to add your branch to the `release_branches` option
