### ISSUE TITLE
 Error: Resource not accessible by integration

### ISSUE THREAD

**Issue by janderssonse** [mathieudutour/github-tag-action#94]
When using this action as suggested in the usage example, I get an fail with 
Error: Resource not accessible by integration

This error has often something to do with the GITHUB_TOKEN access I read from some googling, but I dunno what can be the problem. The repo is main, the commiter is me, all accesses are given to the repo, (as default).

CI-file

https://raw.githubusercontent.com/janderssonse/homebrew-avtools2/main/.github/workflows/publish.yaml

I would really like to fix this, as I like the conventional commit features your action has. Any suggestions?

**Comment by qcastel** [comment]
I had the same issue on a vanilla repo and this is what I had to change:

![Screenshot 2023-12-22 at 12 07 52](https://github.com/mathieudutour/github-tag-action/assets/3748231/73cc739c-6b92-4c81-b7da-794ab99d6f30)

`Read and write permissions`
